version: "1.0"

services:
  keycloak:
    image: bitnami/keycloak:20.0.5-debian-11-r8
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=P&g?@^,wDTNX4]zM
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=Wjd4nw37wJu9bAsvBv3Mn8byew7URykL
    depends_on:
      - postgresql

    restart: on-failure

  nginx:
    image: nginx:mainline-alpine-slim
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/certs/certs:/etc/letsencrypt
    ports:
      - 443:443
      - 80:80
    depends_on:
      - keycloak
      - client
      - api
      - postgresql

  api:
    image: ducluongvn/api
    depends_on:
      - postgresql
    restart: on-failure

  client:
    image: ghcr.io/luongnguyentrong/lvtn_client:master
    depends_on:
      - keycloak

  postgresql:
    image: postgres:15.2-alpine3.17
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=R#iB69xJL8V3q%VTwSdRj4vBNdi#XlSv
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ${PWD}/postgresql/:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
