services:
  keycloak:
      image: jboss/keycloak:15.1.1
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: P&g?@^,wDTNX4]zM
      ports:
        - 8080:8080

  nginx:
      image: ducluongvn/console:lastest
      volumes:
        - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
        - ${PWD}/certs:/etc/letsencrypt
      ports:
        - 443:443
        - 80:80

  postgres:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432