CREATE DATABASE metadata;

CREATE SCHEMA keycloak;
CREATE USER keycloak WITH PASSWORD 'Wjd4nw37wJu9bAsvBv3Mn8byew7URykL';
GRANT ALL PRIVILEGES ON SCHEMA keycloak TO keycloak;

CREATE USER khoa WITH PASSWORD '7jySGi9Yj6jX9A12lijb5wsPntUiPdU8';
ALTER USER khoa WITH SUPERUSER;

CREATE USER api_server WITH PASSWORD '634ZgwXWSjVt5179XimSMkhmg2Uxnq5Q';
ALTER USER api_server WITH SUPERUSER;